Could not find GLIMDA.
/RunPrep.py:86: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  kTLnat[9:12] = kTLnat[9:12]*5
/RunPrep.py:511: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  mExp_mpc[indsccx]=17;
/RunPrep.py:549: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  kTCleak = kTCleak.as_matrix()
/gm.py:100: RuntimeWarning: invalid value encountered in true_divide
  TFa=(TAs/tck50as)**tcnas;
/gm.py:105: RuntimeWarning: invalid value encountered in true_divide
  TFr=(TRs/tck50rs)**tcnrs;
Traceback (most recent call last):
  File "assimulo/solvers/../lib/sundials_callbacks_ida_cvode.pxi", line 240, in assimulo.solvers.sundials.cv_jac
  File "/nc_createODEs.py", line 28, in jac
    return self.Jeval774(t,x,self.dataS)
  File "/Jeval774.py", line 7221, in Jeval774
    Je[67,67]=-(1000000000000*Vv384*np.conj(k467)*np.conj(k551) + 1000000000000*Vv383*np.conj(k467)*np.conj(k526)*np.conj(x67) + (1000000000000*Vv388*np.conj(k467)*np.conj(k601)*np.conj(x72))/(np.conj(k474) + np.conj(x68)) - (1000000000000*Vv388*np.conj(k467)*np.conj(k601)*np.conj(x68)*np.conj(x72))/(np.conj(k474) + np.conj(x68))**2)/(1000000000000*Vx68);
  File "/opt/conda/lib/python3.7/site-packages/numpy/matrixlib/defmatrix.py", line 213, in __mul__
    if isinstance(other, (N.ndarray, list, tuple)) :
KeyboardInterrupt
Traceback (most recent call last):
  File "./test2.py", line 19, in <module>
    [t, xoutG, xoutS] = RunModel(flagD, th, STIM, [], [], dataS, dataG, dataG.kTCleak, dataG.kTCmaxs)
  File "/RunModel.py", line 247, in RunModel
    t1, xoutS = exp_sim.simulate(ts_up, 1)
  File "assimulo/ode.pyx", line 168, in assimulo.ode.ODE.simulate
  File "assimulo/ode.pyx", line 288, in assimulo.ode.ODE.simulate
  File "assimulo/explicit_ode.pyx", line 101, in assimulo.explicit_ode.Explicit_ODE._simulate
  File "assimulo/explicit_ode.pyx", line 187, in assimulo.explicit_ode.Explicit_ODE._simulate
  File "assimulo/solvers/sundials.pyx", line 1894, in assimulo.solvers.sundials.CVode.integrate
  File "assimulo/solvers/sundials.pyx", line 1964, in assimulo.solvers.sundials.CVode.integrate
assimulo.solvers.sundials.CVodeError: 'The linear solvers setup function failed in an unrecoverable manner. At time 17940.000000.'
